name: hello-docker
on: [push]

jobs:
  build:
    env:
      CGO_ENABLED: 0
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v2-beta
        with:
          go-version: 1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: go build -o dist/run src/main.go

      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist/

#      - name: Run ls
#        run: ls
#      - name: Check dir
#        run: |
#          cd dist
#          ls
#      - name: Run
#        run: ./dist/hello
#      - name: Check go version
#        run: go version
#      - name: Run
#        run: dist/hello