name: hello-docker
on: [push]
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  CGO_ENABLED: 0
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v2-beta
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

#      - name: Check go version
#        run: go version

      - name: Build
        run: go build -o dist/hello src/main.go

      - name: Run
        run: dist/hello

      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist/

#      - name: Docker build
#        run: docker image build -f test.Dockerfile -t $DOCKER_USERNAME/$GITHUB_WORKFLOW:$GITHUB_RUN_ID .
#
#      - name: Docker login
#        run: docker login -u $DOCKER_USERNAME --password $DOCKER_PASSWORD
#
#      - name: Docker push
#        run: docker image push $DOCKER_USERNAME/$GITHUB_WORKFLOW:$GITHUB_RUN_ID

#    - name: Get dependencies
#      run: |
#        go get -v -t -d ./...

#  run:
#    name: run
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Download build
#        uses: actions/download-artifact@v1
#        with:
#          name: dist
#
#      - name: Run ls
#        run: ls
#
#      - name: Check dir
#        run: |
#          cd dist
#          ls
#
#      - name: Run
#        run: ./dist/hello
