name: hello-docker
on: [push]

jobs:
  deploy:
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: Docker build
        run: docker image build -f Dockerfile -t $DOCKER_USERNAME/$GITHUB_WORKFLOW:$GITHUB_RUN_NUMBER .

      - name: Docker login
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Docker push
        run: docker image push $DOCKER_USERNAME/$GITHUB_WORKFLOW:$GITHUB_RUN_NUMBER

#      - name: Run ls
#        run: ls
#      - name: Check dir
#        run: |
#          cd dist
#          ls
#      - name: Run
#        run: ./dist/hello
#      - name: Check go version
#        run: go version
#      - name: Run
#        run: dist/hello