name: Go
on: [push]
env:
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  CGO_ENABLED: 0
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v2-beta
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Check go version
      run: go version

#    - name: Check docker version
#      run: docker version

#    - name: Get dependencies
#      run: |
#        go get -v -t -d ./...
    - name: Build
      run: go build -o hello ./src/main.go

    - name: Run ls
      run: ls

    - name: Run
      run: ./hello
